### ISSUE TITLE
The Game Crashes When Launched

### ISSUE THREAD

**Issue by Unk88816** [glufy100/Pulse-Addon#8]
When i open the game it crashes. I fixed the mixin incompatibility between meteor and pulse addon but this time i probably must downgrade java version to probably 11 but i can't. (Edit: error is about mixins i guess) Also if you can please give the crash fixed jar file

**Comment by Unk88816** [comment]
I even edited the source code to match with java 21.0.5 (the version i use) but even that doesn't work. If there areString[] additionalArgs on ModuleMixin class file it might be edited and if it is edited please send us the jar file that works

**Comment by glufy100** [comment]
I used the jar that is on GitHub. Oh wait I have a idea I removed a mixing from meteor client that make the game crash when using crack.

**Comment by Unk88816** [comment]
so can you send the jar file?

**Comment by Unk88816** [comment]
nevermind you can just send the location to the mixin

**Comment by Unk88816** [comment]
i mean like Glufy/Pulse/...

**Comment by glufy100** [comment]
[Pulse-2.1.1.zip](https://github.com/user-attachments/files/17924072/Pulse-2.1.1.zip)
here is the mod in zip

**Comment by Unk88816** [comment]
thanks :)

**Comment by Unk88816** [comment]
i'll try something

**Comment by glufy100** [comment]
With the official meteor client it is crashing because of this line YggdrasilMinecraftSessionServiceAccessor in the mixing config. I used a client with out this. I just tryed with the official client and it is crashing. Go and see on my github they should be a clone of the meteor client repo with the change. 
[meteor-client-0.5.8 (3).zip](https://github.com/user-attachments/files/17924133/meteor-client-0.5.8.3.zip)

**Comment by glufy100** [comment]
here is a dowload of the client with the modification

**Comment by Unk88816** [comment]
THANKS SO MUCH :D

**Comment by Unk88816** [comment]
it didn't crash

**Comment by Unk88816** [comment]
also the addon might be the best addon to me it looks like it covers everything i want :D

**Comment by glufy100** [comment]
if you have a idea on why it is crashing let me know it.

**Comment by Unk88816** [comment]
the bad part is when a person looks a the logs it looks like only the ModuleMixin class file is bugged you might need to fix it ;) and the even worse part is you get a different crash log next time like you fixed the first issue (It migght be becuase i asked all of them to ChatGPT)
